// Inglés de la interfaz. Clave = texto original en español.
// (El contenido entre llaves es JSON válido: lo comprueba herramientas/claves_interfaz.py.)
export default {
  "{0} juegos": "{0} games",
  "Respaldar": "Back up",
  "Restaurar…": "Restore…",
  "Abrir carpeta del save": "Open save folder",
  "Abrir carpeta del backup": "Open backup folder",
  "Subir a {0}": "Upload to {0}",
  "Subir a la nube (no conectada)": "Upload to the cloud (not connected)",
  "Detalles": "Details",
  "Diagnóstico": "Diagnosis",
  "Verificar la copia": "Verify the copy",
  "Quitar carpeta manual": "Remove manual folder",
  "Ocultar": "Hide",
  "Arrancando el motor…": "Starting the engine…",
  "Modo demostración · datos de ejemplo": "Demo mode · sample data",
  "escaneo en {0} s": "scan in {0} s",
  "Descargando de la nube": "Downloading from the cloud",
  "Cancelar": "Cancel",
  "Deseleccionar": "Deselect",
  "Seleccionar todos": "Select all",
  "Ningún juego seleccionado": "No game selected",
  "1 juego seleccionado": "1 game selected",
  "{0} juegos seleccionados": "{0} games selected",
  "clic: marcar · doble clic: detalles · clic derecho: más": "click: select · double-click: details · right-click: more",
  "Conecta una nube primero": "Connect a cloud first",
  "Subir": "Upload",
  "Restaurar": "Restore",
  "Espacio libre en el disco de la carpeta de backups": "Free space on the backup folder drive",
  "{0} libres en {1}": "{0} free on {1}",
  "Abrir": "Open",
  "Cambiar": "Change",
  "Principal": "Main",
  "Conectado a {0}": "Connected to {0}",
  "Conectar": "Connect",
  "Gestionar": "Manage",
  "Ayuda": "Help",
  "Mis partidas": "My saves",
  "Nube": "Cloud",
  "Juegos ocultos": "Hidden games",
  "Juegos sin launcher": "Games without a launcher",
  "Verificar copias": "Verify copies",
  "Estadísticas BD": "Database stats",
  "Instrucciones": "User guide",
  "Registro (log)": "Log",
  "Opciones": "Options",
  "Apoyar el proyecto": "Support the project",
  "Programa": "Program",
  "Base de datos": "Database",
  "Estado": "Status",
  "Buscar juego…  (Ctrl+F)": "Search game…  (Ctrl+F)",
  "Añadir una carpeta de partidas a mano": "Add a save folder by hand",
  "Añadir": "Add",
  "Escaneando": "Scanning",
  "Escanear": "Scan",
  "Comprueba la base de datos y sincroniza la nube": "Checks the database and syncs the cloud",
  "Actualizar": "Update",
  "¿Qué copia quieres restaurar?": "Which copy do you want to restore?",
  "{0} copias de seguridad de “{1}”": "{0} backups of “{1}”",
  "Restaurar esta copia": "Restore this copy",
  "La más reciente": "The most recent",
  "Recomendado": "Recommended",
  "Elegir otra copia de la lista →": "Choose another copy from the list →",
  "Antes de restaurar, ASH guarda tu partida actual como “↩️ Antes de restaurar”.": "Before restoring, ASH keeps your current save as “↩️ Before restoring”.",
  "Aceptar": "OK",
  "Empezar": "Get started",
  "Bienvenido. Arlequin SaveHub localiza, respalda y restaura las partidas guardadas de tus juegos.": "Welcome. Arlequin SaveHub finds, backs up and restores the saves of your games.",
  "¿Dónde guardamos tus copias?": "Where should we keep your backups?",
  "En el Escritorio (recomendado)": "On the Desktop (recommended)",
  "Elegir otra carpeta…": "Choose another folder…",
  "Ayudar a mejorar Arlequin de forma anónima": "Help improve Arlequin anonymously",
  "Comparte las rutas de guardado que ASH descubre para juegos que la base de datos aún no conoce. Nunca tus partidas ni tu nombre de usuario. Puedes cambiarlo cuando quieras en Opciones.": "Shares the save paths ASH discovers for games the database does not know yet. Never your saves or your user name. You can change it anytime in Options.",
  "¿Qué se envía exactamente?": "What exactly is sent?",
  "Copiado": "Copied",
  "Copiar": "Copy",
  "Cerrar": "Close",
  "manual": "manual",
  "Buscando tus juegos…": "Looking for your games…",
  "Ningún juego coincide con “{0}”.": "No game matches “{0}”.",
  "No hay juegos que mostrar con este filtro.": "There are no games to show with this filter.",
  "Juego": "Game",
  "Tienda": "Store",
  "Local": "Local",
  "Tamaño": "Size",
  "Último backup": "Last backup",
  "con copia local": "with a local copy",
  "{0} sin proteger": "{0} unprotected",
  "{0} juegos subidos": "{0} games uploaded",
  "{0} sin subir": "{0} not uploaded",
  "Todo al día": "All up to date",
  "Guarda tus copias en Google Drive, OneDrive o Dropbox.": "Keep your backups in Google Drive, OneDrive or Dropbox.",
  "Conectar una nube": "Connect a cloud",
  "ninguno": "none",
  "Disco de la carpeta de backups ({0}): {1} libres de {2}": "Backup folder drive ({0}): {1} free of {2}",
  "Disco {0} · de {1}": "Drive {0} · of {1}",
  "{0} libres": "{0} free",
  "Partidas detectadas": "Detected saves",
  "Protegidas": "Protected",
  "En la nube": "In the cloud",
  "Tus partidas ocupan": "Your saves take up",
  "Texto": "Text",
  "Hola {0}": "Hello {0}",
  "se creará en: {0}": "will be created in: {0}",
  "Verificar": "Verify",
  "Este juego ya no está en la lista (quizá cambió tras un escaneo).": "This game is no longer in the list (it may have changed after a scan).",
  "Escaneando… los datos se actualizarán al terminar.": "Scanning… the data will update when it finishes.",
  "1 copia local": "1 local copy",
  "{0} copias locales": "{0} local copies",
  "{0} en la nube": "{0} in the cloud",
  "carpeta manual": "manual folder",
  "sin ruta respaldable": "no path to back up",
  "Dónde guarda la partida": "Where it saves",
  "No hay una ruta de save local respaldable.": "There is no local save path that can be backed up.",
  "{0} · modificado {1}": "{0} · modified {1}",
  "La carpeta no existe todavía": "The folder does not exist yet",
  "Copias locales": "Local copies",
  "Todavía no hay ninguna copia.": "There are no copies yet.",
  "Instalado en": "Installed in",
  "Cómo se detectó": "How it was detected",
  "Confianza": "Confidence",
  "No aparecen en la lista. Marca los que quieras volver a mostrar.": "They are not shown in the list. Select the ones you want to show again.",
  "Volver a mostrar": "Show again",
  "No tienes ningún juego oculto.": "You have no hidden games.",
  "Cada subcarpeta de estas rutas se trata como un posible juego (DRM-free, portables…) y se cruza con la base de datos.": "Each subfolder of these paths is treated as a possible game (DRM-free, portable…) and matched against the database.",
  "Quitar": "Remove",
  "Añadir carpeta": "Add folder",
  "Cerrar y reescanear": "Close and rescan",
  "Todavía no has añadido ninguna carpeta.": "You have not added any folder yet.",
  "Apoya Arlequin SaveHub": "Support Arlequin SaveHub",
  "Arlequin es gratuito y open source. Si te resulta útil, puedes ayudarme a seguir mejorándolo y manteniendo la base de datos.": "Arlequin is free and open source. If you find it useful, you can help me keep improving it and maintaining the database.",
  "Apoyar con PayPal": "Support with PayPal",
  "Código en GitHub": "Code on GitHub",
  "Gracias por apoyar el proyecto ❤️": "Thanks for supporting the project ❤️",
  "Conecta una cuenta para guardar tus backups en la nube. ASH solo puede ver y modificar los archivos que crea él mismo.": "Connect an account to keep your backups in the cloud. ASH can only see and change the files it creates itself.",
  "Esperando al inicio de sesión en tu navegador…": "Waiting for you to sign in in your browser…",
  "Iniciar sesión en el navegador": "Sign in in the browser",
  "Conectar →": "Connect →",
  "Se abrirá la página oficial de inicio de sesión en tu navegador. Solo se puede tener una nube conectada a la vez.": "The official sign-in page will open in your browser. Only one cloud can be connected at a time.",
  "Sin respuesta": "No response",
  "Igual que la local": "Same as local",
  "Distinta a la local": "Different from local",
  "No está en este PC": "Not on this PC",
  "Volver": "Back",
  "Buscar…": "Search…",
  "Marcar todo": "Select all",
  "Ninguno": "None",
  "No se pudo cargar la lista: {0}": "The list could not be loaded: {0}",
  "No hay backups en la nube todavía.": "There are no backups in the cloud yet.",
  "{0} copias": "{0} copies",
  "1 copia": "1 copy",
  "(última)": "(latest)",
  "Se guardan en tu carpeta de backups. Si ya tienes una copia local de ese juego, no se borra: pasa a copia histórica con fecha.": "They are saved in your backup folder. If you already have a local copy of that game, it is not deleted: it becomes a dated copy.",
  "Descargar": "Download",
  "Estado de la nube disponible": "Cloud status available",
  "Sincronizando con {0}…": "Syncing with {0}…",
  "Descargar backups de {0}": "Download backups from {0}",
  "Marca los juegos a descargar. Se verifica cada copia antes de guardarla.": "Select the games to download. Each copy is verified before it is saved.",
  "Sin conectar": "Not connected",
  "Cuenta desconocida": "Unknown account",
  "Última subida:": "Last upload:",
  "Nunca": "Never",
  "Consultando espacio…": "Checking space…",
  "Desconectar": "Disconnect",
  "Subir ahora": "Upload now",
  "Las copias locales que falten o hayan cambiado": "The local copies that are missing or have changed",
  "Traer copias de la nube a este PC": "Bring copies from the cloud to this PC",
  "Sincronizar": "Sync",
  "Actualizar qué copias hay en la nube": "Refresh which copies are in the cloud",
  "Las subidas automáticas y los límites se configuran en Opciones → Nube.": "Automatic uploads and limits are set in Options → Cloud.",
  "Ningún juego excluido": "No game excluded",
  "1 juego excluido": "1 game excluded",
  "{0} juegos excluidos": "{0} games excluded",
  "Los juegos marcados se excluyen de este modo. Los demás se incluyen.": "The selected games are excluded from this mode. The rest are included.",
  "Excluir todos": "Exclude all",
  "No hay juegos.": "There are no games.",
  "{0} excluidos de {1}": "{0} excluded of {1}",
  "No se pudieron guardar las opciones.": "The options could not be saved.",
  "Sin límite": "No limit",
  "Los cambios se aplican al pulsar Guardar.": "Changes are applied when you press Save.",
  "Instrucciones avanzadas": "Advanced instructions",
  "Abre la ventana de opciones de la versión 1.1.x": "Opens the options window of version 1.1.x",
  "Ventana clásica": "Classic window",
  "Guardar": "Save",
  "Automático ({0})": "Automatic ({0})",
  "Esperar": "Wait",
  "min de inactividad": "idle minutes",
  "No disponible": "Not available",
  "Ver qué se enviaría": "See what would be sent",
  "Último envío: {0}": "Last sent: {0}",
  "Cada": "Every",
  "No hay ninguna nube conectada: estas opciones se aplicarán cuando conectes una.": "No cloud is connected: these options will apply once you connect one.",
  "Más de": "More than",
  "Lo que se enviaría": "What would be sent",
  "Inicio": "Startup",
  "Idioma": "Language",
  "En automático se usa el idioma de Windows.": "In automatic mode, the Windows language is used.",
  "Abrir Arlequin SaveHub con Windows": "Open Arlequin SaveHub with Windows",
  "Abrir minimizado cuando inicie Windows": "Open minimized when Windows starts",
  "Arranca directamente en la bandeja del sistema.": "Starts directly in the system tray.",
  "Ocultar en la bandeja del sistema al minimizar": "Hide in the system tray when minimized",
  "Comprobar si hay una versión nueva al iniciar": "Check for a new version at startup",
  "En esta beta las actualizaciones del programa se instalan a mano.": "In this beta, program updates are installed by hand.",
  "Avisos de tareas automáticas": "Notifications for automatic tasks",
  "Cuándo avisar al terminar un respaldo o una subida automática.": "When to notify you after an automatic backup or upload.",
  "Lista y rendimiento": "List and performance",
  "Mostrar juegos instalados sin save conocido": "Show installed games without a known save",
  "Mostrar juegos a la espera de su primer uso": "Show games waiting for their first use",
  "Mostrar juegos 100% online": "Show 100% online games",
  "Su progreso se guarda en el servidor.": "Their progress is stored on the server.",
  "Aplazar el cálculo SHA-256 hasta que el PC esté inactivo": "Postpone SHA-256 checks until the PC is idle",
  "Lo usan los backups locales y la nube.": "Used by local backups and the cloud.",
  "Ayuda a mejorar Arlequin": "Help improve Arlequin",
  "Compartir las rutas de guardado que aprende ASH": "Share the save paths ASH learns",
  "Envía de forma anónima las carpetas de partidas que ASH encuentra (o que añades a mano) para juegos que la base de datos aún no conoce, y qué juegos instalados no tienen ruta. Se comparan con las de otros usuarios para mejorar ArlequinGameDB. Nunca se envían tus partidas ni tu nombre de usuario.": "Anonymously sends the save folders ASH finds (or that you add by hand) for games the database does not know yet, and which installed games have no path. They are compared with other users' to improve ArlequinGameDB. Your saves and your user name are never sent.",
  "Respaldos automáticos": "Automatic backups",
  "Hacer un respaldo periódico": "Make a periodic backup",
  "Solo si el PC está inactivo": "Only if the PC is idle",
  "Si estás usando el PC, el respaldo periódico se aplaza.": "If you are using the PC, the periodic backup is postponed.",
  "Respaldar los juegos cuando se cierren": "Back up games when they close",
  "Actúa al detectar ABIERTO → CERRADO. Si detecta un crash, protege el último backup válido y no copia el save sospechoso.": "Acts on detecting OPEN → CLOSED. If it detects a crash, it protects the last valid backup and does not copy the suspicious save.",
  "Copias": "Copies",
  "Máximo de copias por juego": "Maximum copies per game",
  "Sin límite = conservar todas las copias históricas.": "No limit = keep every dated copy.",
  "Guardar lo que había antes de restaurar": "Keep what was there before restoring",
  "Crea la copia “↩️ Antes de restaurar” para poder deshacer.": "Creates the “↩️ Before restoring” copy so you can undo.",
  "Comprobar la integridad de las copias cada semana": "Check the integrity of the copies every week",
  "Se hace con el PC inactivo; solo avisa si encuentra problemas.": "Runs while the PC is idle; only notifies you if it finds problems.",
  "No copiar estos archivos o carpetas": "Do not copy these files or folders",
  "Separados por ; — ejemplo: *.log; *.tmp; ShaderCache; Crashes. Ocupan menos, pero al restaurar no se recuperan.": "Separated by ; — example: *.log; *.tmp; ShaderCache; Crashes. Backups take less space, but those files are not recovered when restoring.",
  "Subidas automáticas": "Automatic uploads",
  "Subir periódicamente": "Upload periodically",
  "Subir al cerrar el juego": "Upload when the game closes",
  "Máximo de copias por juego en la nube": "Maximum copies per game in the cloud",
  "Red y compresión": "Network and compression",
  "Límite de velocidad de subida": "Upload speed limit",
  "0 = sin límite.": "0 = no limit.",
  "No subir con conexiones de uso medido": "Do not upload on metered connections",
  "Compresión ZIP": "ZIP compression",
  "Rápido = menos CPU · Máximo = menos tamaño.": "Fast = less CPU · Maximum = smaller size.",
  "Protección": "Protection",
  "Bloquear la subida si el tamaño cambia demasiado": "Block the upload if the size changes too much",
  "Respecto a la copia anterior: evita subir un save que parece dañado.": "Compared with the previous copy: avoids uploading a save that looks damaged.",
  "No subir a la nube mientras OBS esté abierto": "Do not upload to the cloud while OBS is open",
  "Grabando o transmitiendo: no gasta red ni disco durante la sesión.": "Recording or streaming: no network or disk is used during the session.",
  "General": "General",
  "Excluir del respaldo periódico": "Exclude from the periodic backup",
  "Excluir del respaldo al cerrar el juego": "Exclude from the backup when the game closes",
  "Excluir de la subida periódica": "Exclude from the periodic upload",
  "Excluir de la subida al cerrar el juego": "Exclude from the upload when the game closes",
  "Recursos que está usando Arlequin SaveHub": "Resources Arlequin SaveHub is using",
  "Rendimiento": "Performance",
  "máx {0}": "max {0}",
  "Recogiendo datos…": "Collecting data…",
  "hace {0} s": "{0} s ago",
  "ahora": "now",
  "{0} núcleos · 100 % = todos a tope": "{0} cores · 100 % = all at full load",
  "{0} % de {1}": "{0} % of {1}",
  "Lectura + escritura (incluye las copias con robocopy)": "Read + write (includes copies made with robocopy)",
  "total {0}": "total {0}",
  "Rendimiento de Arlequin SaveHub": "Arlequin SaveHub performance",
  "Lo que está usando ASH ahora mismo (el motor, la interfaz y las copias). Últimos 2 minutos.": "What ASH is using right now (the engine, the interface and the copies). Last 2 minutes.",
  "La medición de recursos solo está disponible en Windows.": "Resource monitoring is only available on Windows.",
  "media": "average",
  "pico": "peak",
  "Por parte del programa": "By part of the program",
  "Parte": "Part",
  "Procesos": "Processes",
  "Disco": "Disk",
  "La red se mide solo en el motor: es donde están la nube y las descargas de la base de datos.": "Network is measured only in the engine: that is where the cloud and the database downloads are.",
  "CPU": "CPU",
  "RAM": "RAM",
  "Red": "Network",
  "Motor (ASH)": "Engine (ASH)",
  "Interfaz (WebView2)": "Interface (WebView2)",
  "Copias (robocopy)": "Copies (robocopy)",
  "Todos": "All",
  "Con copia": "With copy",
  "Sin copia": "Without copy",
  "Sin subir": "Not uploaded",

  "Sin launcher": "No launcher",
  "Desinstalado": "Uninstalled",
  "Juego sin Launcher": "Game without Launcher",
  "Otros": "Others",
  "Sin Datos de Guardado Conocidos": "No Known Save Data",
  "Juegos 100% Online": "100% Online Games",
  "Instalados - a la Espera de Primer Uso": "Installed - Waiting for First Use",
  "Sin Launcher Conocido": "No Known Launcher",
  "Carpetas Añadidas Manualmente": "Manually Added Folders",
  "Solo en Carpeta Backup": "Only in the Backup Folder",
  "la base de datos no registra save para estos": "the database has no save data for these",
  "el progreso se guarda en el servidor": "progress is stored on the server",
  "encontrado por su ruta de guardado": "found by its save path",
  "sin datos de guardado": "no save data",
  "ruta prevista": "expected path",
  "DESINSTALADOS": "UNINSTALLED",
  "ALTA": "HIGH",
  "MEDIA": "MEDIUM",
  "BAJA": "LOW",
  "confianza alta": "high confidence",
  "confianza media": "medium confidence",
  "confianza baja": "low confidence",
  "sin launcher": "no launcher",
  "instalado": "installed",
  "sin save conocido": "no known save",
  "Solo errores": "Only errors",
  "Siempre": "Always",
  "horas": "hours",
  "días": "days",
  "semanas": "weeks",
  "Rápido": "Fast",
  "Equilibrado": "Balanced",
  "Máximo": "Maximum",
  "Sí": "Yes",
  "No": "No",
  "Reintentar": "Retry",
  "hoy {0}": "today {0}",
  "ayer {0}": "yesterday {0}",
  "hace {0} días": "{0} days ago"
}
